### ISSUE TITLE
99.6 existing.CytoscapeWindow failed to connect

### ISSUE THREAD

**Issue by m-grimes** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#12]
This still doesn't work with the new version installed.

>   k1.w <- existing.CytoscapeWindow("Case 1 Pathway", copy=T)
> Error in function (type, msg, asError = TRUE)  : 
>   Failed to connect to localhost port 9000: Connection refused
> getWindowList(cy)
> [1] "Case 1 CCCN"    "Case 1 Pathway" "Case 3 Pathway" "Case 2 Pathway" "Case 5 Pathway"
> sessionInfo()
> R version 3.2.0 (2015-04-16)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] parallel  stats4    grid      stats     graphics  grDevices utils     datasets 
 [9] methods   base     

other attached packages:
 [1] RCy3_0.99.6      ...

**Comment by tmuetze** [comment]
This error ("Failed to connect to localhost port 9000: Connection refused") looks like an old version, as the new version should connect to port 1234. Is it possible that RCy3 is interfering with RCytoscape as RCytoscape uses port 9000?
