### ISSUE TITLE
saveImage function fails

### ISSUE THREAD

**Issue by stefanavey** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#22]
The `saveImage` function was changed with commit https://github.com/tmuetze/Bioconductor_RCy3_the_new_RCytoscape/commit/3f6634262b270fb503169b5117aa21c3aa042db3 : "Paul's update to v 24"

Is there a reason that these lines were commented out?

```
#request.res <- GET(resource.uri, write_disk(paste0(file.name,".", image.type)))
#write (sprintf ('saving image to %s.%s', file.name, image.type), stderr ())
```

Currently the function fails silently because it creates the `resource.uri` and does nothing with it.

**Comment by tmuetze** [comment]
Hi @stefanavey , Thanks for pointing this out. There is no reason for this. I commented the lines back in and made sure it works.
