### ISSUE TITLE
Adding Roxygen comments to RCy3.R to give package help documentation?

### ISSUE THREAD

**Issue by jooolia** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#24]
Would it be ok to add roxygen comments to RCy3.R with the goal of automatically generating a help page for RCy3 with devtools? Currently `help(RCy3)` and `??RCy3`  contain no documentation. The other option would be to manually make a .Rd file. I am happy to contribute either or something else that is thought to work best with the package.

**Comment by tmuetze** [comment]
Absolutely!
