### ISSUE TITLE
hideSelectedEdges() does not work

### ISSUE THREAD

**Issue by St-Hakky** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#36]
I’ve noticed that hideSelectedEdges() doesn’t work. When I use it and hide selected edges, any edges is not hide.

I also checked the following code that is in the reference of RCy3 in bioconductor, and I found it doesn’t work.

```
# first, delete existing windows to save memory:
deleteAllWindows(CytoscapeConnection())
cw <- CytoscapeWindow ( hideSelectedEdges.test , graph=makeSimpleGraph())
displayGraph (cw)
layoutNetwork(cw,  grid )
selectEdges (cw,  B (synthetic lethal) C )
hideSelectedEdges (cw)
```

You can check the same code in the following URL. https://www.bioconductor.org/packages/release/bioc/manuals/RCy3/man/RCy3.pdf

Thanks

**Comment by tmuetze** [comment]
You'd want to wrap window names, layout types and edges names in quotation marks. Could you check that you are on the latest versions or the versions named in DESCRIPTION and please ensure that you have the latest version of CyREST installed. If this does not solve your problem, what versions are you on and what error do you get?
