### ISSUE TITLE
Support on non-linux systems

### ISSUE THREAD

**Issue by ahmohamed** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#38]
Is there a reason RCy3 is not supported on MacOS and Windows? I have noticed this is a recent change since Bioc 3.3

**Comment by tmuetze** [comment]
@ahmohamed: You are referring to the missing links on https://www.bioconductor.org/packages/release/bioc/html/RCy3.html, correct? RCy3 is supported on OS X and Windows. The build system is only setup to run on Linux to save resources. I will investigate to find out why the links are missing. Thanks for pointing this out!

**Comment by ahmohamed** [comment]
@tmuetze Thanks for getting back to me. I am trying to use RCy3 in my package [NetPathMiner](https://www.bioconductor.org/packages/release/bioc/html/NetPathMiner.html) instead of the deprecated RCytoscape. I would also like to keep the support to all platforms.

I have noticed the .BBSoptions file committed (by Dan) to the [Bioc-mirror repo](https://github.com/Bioconductor-mirror/RCy3/tree/master) mark it as unsupported. I guess that's why there are no binaries built for Mac and Windows.

Also, you may need to look at the Devel version since the [build system](http://bioconductor.org/checkResults/3.4/bioc-LATEST/RCy3/zin1-buildsrc.html) is giving an error.

Thanks again.

**Comment by tmuetze** [comment]
@ahmohamed The problem is fixed now and the errors and the missing support should be gone with the next build on the build system.

**Comment by ahmohamed** [comment]
Awesome, I will give it a swirl and update my code. Thanks a lot.

**Comment by tmuetze** [comment]
No worries. Let us know if there is anything else.
