### ISSUE TITLE
Support of nonsimple graphs?

### ISSUE THREAD

**Issue by magnuspalmblad** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#41]
Dear RCy3 team,

Is there any way to work with nonsimple graphs in RCy3? I read in the graphNEL documentation that "although this representation can support multi-edges, such support is not implemented and instances of graphNEL are assumed to be simple graphs with at most one edge between any pair of nodes", so I guess the limitation comes from there. The adjacency matrix representations clearly wouldn't be any better. But perhaps there is a trick or workaround I haven't found?

RCy3 is a very nice interface between R and Cytoscape, but not supporting nonsimple graphs is a rather serious limitation I would say (ruling out anything from the Seven Bridges of Königsberg to the BioGRID interactomes).

Magnus

**Comment by AlexanderPico** [comment]
Hi Magnus,

There is a new version of RCy3 in the works that will be independent of the graphNEL object model. With it, you will be able to pass network models back and forth between Cytoscape and R as data frames, iGraphs or as graphNELs per your needs. You no longer *need* to maintain a graph model in R at all, in fact.

The new repo is here: https://github.com/cytoscape/RCy3 

It's not yet released, but if you want to be an early tester with your use case (9 months later), just let me know and we can make sure the new version works for you.
